### ISSUE TITLE
More detailed values for duration and distance

### ISSUE THREAD

**Issue by FelixMoelder** [timfraedrich/OutRun#18]
In the workout summary the workout duration and distances are only shown as rounded values.
E.g. if my workout took me 1:39h it is shown as 2hours.
Same goes for distances being shown as full kilometer values.

I don't see a reason why durations should not show the precise value and distances are not represented by at least one or maybe two decimal places.

Changing this should not be an issue as there is enough space and it would help comparing workouts to each other.

**Comment by timfraedrich** [comment]
The way it is right now is purely for aesthetic reasons, I tried putting one or even two decimal places in the view, but it just did not look good.

I will address your issue with #19 though.
