### ISSUE TITLE
Add a decimal point (or two) in the home screen of a workout

### ISSUE THREAD

**Issue by Duckbilled** [timfraedrich/OutRun#25]
At the moment the home screen shows the list of workouts and a round-up distance. I would like to have it at least round-up to a decimal point. So instead of 2km to 2.4km. I feel 400 meters is quite a difference.

![19D836E3-0D6D-479C-A8EF-FCDA3E2A4A0F](https://user-images.githubusercontent.com/52334713/92994872-9791b280-f4fe-11ea-915c-a44092b6eea9.png)

**Comment by timfraedrich** [comment]
See #18 and #19
