### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by mjunkmyjunk** [timfraedrich/OutRun#38]
XCODE 12.0.1

Have done
sudo gems update cocoapods
pod update (on the downloaded files directory)
```
Update all pods
Updating local specs repositories
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
Analyzing dependencies
Downloading dependencies
Installing Cache (6.0.0)
Installing Charts (3.6.0)
Installing CoreGPX (0.8.1)
Installing CoreStore (6.3.2)
Installing SnapKit (5.0.1)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `OutRun.xcworkspace` for this project from now on.
Pod installation complete! There are 5 dependencies from the Podfile and 5 total pods installed.
```

trying to run it locally on simulator churned out quite a few build issue.

<img width="2025" alt="Screenshot 2020-10-17 at 3 38 45 PM" src="https://user-images.githubusercontent.com/56195569/96331300-db904e00-108e-11eb-977d-bc07c4d91d4b.png">

Would appreciate some guidance on what's happening. 

```
/// the disk storage as basis of the caching system
    private let diskStorage: DiskStorage<UIImage>?
```

clicking no the error declaration points to this

```
/// Save objects to file on disk
final public class DiskStorage<Key: Hashable, Value> {
  enum Error: Swift.Error {
    case fileEnumeratorFailed
  }
```

is there a missing "value"? 

Thanks

**Comment by timfraedrich** [comment]
I just saw that the caching framework I’m using has changed their API a bit, so I will need to update the code you’re referring to, for now you can just add `String` before `UIImage` as a key parameter, that will fix it.

**Comment by mjunkmyjunk** [comment]
Thanks for the quick reply. it works.

there's one more line tho that spits out an error.

<img width="1639" alt="Screenshot 2020-10-17 at 5 56 33 PM" src="https://user-images.githubusercontent.com/56195569/96334330-83634700-10a2-11eb-80d2-87935b56b611.png">

adding the same thing as what you suggested.

            let disk = try DiskStorage<String, UIImage>(config: diskConfig, transformer: TransformerFactory.forImage())

Successful compile! 

Thanks for making this open source, I'm "looking at the code" to learn and see what I can do for myself

**Comment by timfraedrich** [comment]
Great to hear! I hope you can learn from it and maybe contribute some day.
