### ISSUE TITLE
Spanish and Catalan translation

### ISSUE THREAD

**Issue by lpla** [timfraedrich/OutRun#42]
**Is your feature request related to a problem? Please describe.**
I would like to contribute translating this app into Spanish and Catalan but I can't enable any language in Weblate.

**Describe the solution you'd like**
I want to ask @timfraedrich to enable those languages in Weblate.

**Describe alternatives you've considered**
None. I love using this app. I want to contribute so that more friends who don't speak English can use it.

**Additional context**
I used to translate open source projects with similar websites (crowdin.net). Also, I speak the three languages I mentioned.

**Comment by timfraedrich** [comment]
Thank you for showing an interest in contributing translations to this project. I am a little confused that you cannot add languages yourself, but I just went ahead and added them.

If you have any other questions or requests, do not hesitate to ask!

**Comment by lpla** [comment]
Thank you!

**Comment by lpla** [comment]
I did an initial translation of all strings in Catalan and Spanish. They could have issues, but I guess it would be easier for me to debug them while using the app.

**Comment by timfraedrich** [comment]
Just for context, is this a request to add the languages so you can debug them, or are you just letting me know?

**Comment by lpla** [comment]
Just letting you know that I did a first round of translations for both languages, in case you expect to do an app update soon.

I also figured out that I needed to add my known languages to my Weblate profile so it allows me to add languages to projects. So, sorry for bothering you with this issue.

**Comment by timfraedrich** [comment]
You didn't bother me at all, but I'm glad we could sort that issue out.

And I will just leave this open for know, let me know when you think the languages are ready to be added to the app.

And again, thank you for contributing.

**Comment by lpla** [comment]
Is it very difficult to update translations in the app if I find anything wrong with already imported strings? I mean, there are some translations that could be incorrect given context but the easy way to check it is reading them in the app. So maybe I modify those translations after you include the languages in the app and I use it for a while.

But translations should be good enough to be understandable for anyone that doesn’t know any English.

**Comment by timfraedrich** [comment]
No that would not be difficult at all, you can just change it on weblate and it will be included in the next update.

And if you feel comfortable that the languages can be included in the app now I will happily add them as soon as I can, just let me know.

**Comment by lpla** [comment]
I did some changes for consistency in Catalan, given that the translation I was using for "Workout" could be a bit long in some cases, as you noted in Weblate comments. Also I checked all translations again for Spanish and Catalan. I even fixed a typo in English strings, so maybe it was badly translated to the other languages.

So, yes, I feel comfortable with the translations right now for a first release.

**Comment by timfraedrich** [comment]
Okay I will publish it as a beta for now, so you can further debug the translations in context, when I have the next update ready I will also include the strings in the public release.

I will comment here once the beta was approved.

**Comment by timfraedrich** [comment]
Sorry I totally forgot to comment, the beta is online for a few days now. I will close this issue for now, if you have any further questions do not hesitate to ask.

**Comment by lpla** [comment]
Sorry for bothering. How should I join the beta? Is there a link for that?

**Comment by timfraedrich** [comment]
Oh sorry, I forgot to mention that I guess. There is a link in the README of this repo, but here you go: https://testflight.apple.com/join/kDqNWBAi

**Comment by lpla** [comment]
Hi! I revised both Catalan and Spanish translations. Now they should be even more consistent and clear. Also, they fit better in iPhone X/XS/XR/11/12 like screens. I don't know about iPhone SE/SE2/8, as I don't have any to test. Cheers.

**Comment by lpla** [comment]
Hi. Sorry for bothering. Is it expected another beta or stable release only with latest translation changes? Or are they going to be included in a release once a new feature is finished? Cheers.

**Comment by timfraedrich** [comment]
Not bothering at all, it's certainly something I have thought about.

First I wanted to publish an update once I can push the changes I have been working on for quite some time, but due to a lot going on in school rn, I might do as you suggested.
