### ISSUE TITLE
No altitude data recorded

### ISSUE THREAD

**Issue by nano9g** [timfraedrich/OutRun#5]
**Describe the bug**
OutRun is not recording altitude data - when viewing a workout, that section is blank.

**To Reproduce**
1. Record and save a workout 
2. View it in history
3. Ascending and Descending both say "0m" and the graph is blank.

**Expected behavior**
Altitude data should be recorded and viewable.

**Screenshots**
![AC7FE7A3-2D53-46B1-B8BC-58D5B8ABDC35](https://user-images.githubusercontent.com/11694945/90014228-8afa1000-dc5b-11ea-8993-8102c1793890.jpeg)

**Device Information (please complete the following information):**
 - iPhone: X
 - OS: 13.6
 - Version 1.2

**Additional context**
This seems to have worked for the very first workout I recorded with OutRun but hasn't worked since. Location permission is set to "While Using".

**Comment by timfraedrich** [comment]
For reference: Are you on the beta or the public release?

Because to my knowledge I fixed the bug before making 1.2 public. 

If you are on a beta, which build are you on?

**Comment by nano9g** [comment]
Sorry about that - I'm on the TestFlight 1.2 beta, which shows in TestFlight as 1.2 (4).

**Comment by timfraedrich** [comment]
No problem, I just panicked a bit. I will publish the current build (6) to Testflight to avoid confusion.
