### ISSUE TITLE
Beta expires next week

### ISSUE THREAD

**Issue by lpla** [timfraedrich/OutRun#56]
**Describe the bug**
Beta version linked in Readme expires next week, so it could create regressions or inconsistencies in the stored data for users using betas that revert to sn old stable release after the expiring date.

**To Reproduce**
1. Go to the beta link
2. Open in TestFlight
3. Check app details

**Expected behavior**
Another beta or stable release should fix that.

**Comment by timfraedrich** [comment]
There are no changes in the data model between the two versions, but I will make sure to release a new version before the current beta expires. Thanks for pointing that out!
