### ISSUE TITLE
Topmost map in History doesn't change when dark mode toggled

### ISSUE THREAD

**Issue by nano9g** [timfraedrich/OutRun#9]
**Describe the bug**
When dark mode is toggled, the very first map in History doesn't switch like the others. If going from light to dark, it will stay light, and vice versa.

**To Reproduce**
1. Go to History
2. Toggle Dark Mode
3. The first map will stay in the previous mode

**Expected behavior**
The first map should change like the others.

**Screenshots**
![78CC9164-F1B9-43D1-9CCE-EBA36B83CD22](https://user-images.githubusercontent.com/11694945/90214419-454d5c80-ddad-11ea-86d6-f855fce72ced.jpeg)

**Device Information (please complete the following information):**
 - iPhone: iPhone X
 - OS: 13.6.1
 - Version: 1.2 (6) beta

**Comment by nano9g** [comment]
It looks like this isn't 100% fixed in 1.2.1. I still have a couple of map thumbnails that are stuck in either dark or light mode.

Restarting the app hasn't made any difference, nor does viewing the full size map in the affected workout.

![3B92D514-28E2-4B01-BDA3-864CD5EEF3C5](https://user-images.githubusercontent.com/11694945/90590431-64753100-e195-11ea-9a93-47180e6d5871.jpeg)
![5461E1A4-85D8-46CE-9158-764CEAD50605](https://user-images.githubusercontent.com/11694945/90590433-65a65e00-e195-11ea-995d-edc9be37ba92.jpeg)

**Comment by timfraedrich** [comment]
The bug is definitely fixed, but the images might still be cached for you. There is not a normal way to clear it under 1.2.1, I should probably add this to settings, but there is a workaround: Click the settings icon in the tab bar 10 times bringing up a sort of debug menu and then click the clear cache button.
