### ISSUE TITLE
Question: difference between walking and hiking.

### ISSUE THREAD

**Issue by cnf** [timfraedrich/OutRun#93]
Hi, I am asking here because I can't find the docs for it, or find the answer elsewhere.

What is the difference between walking and hiking in the context of this app? Are certain things calculated differently?

Thanks for a great app!

**Comment by timfraedrich** [comment]
There is no difference in the way the app handles both of these activities. It is simply a way to categorise the two different types of activities.

**Comment by cnf** [comment]
ok, thank you! sorry for taking up a ticket for this!
